select top 20 * from customer

-- Top 5 most purchased items
SELECT TOP 5 item_purchased, COUNT(*) as times_bought
FROM customer
GROUP BY item_purchased
ORDER BY times_bought DESC;

-- q1: what is total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender
order by sum(purchase_amount)

--q2: which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- q3: which are the top 5 products with the highest average review rating?
select top 5 item_purchased, round(avg(review_rating),2) as "Average Product Review"
from customer
group by item_purchased
order by avg(review_rating) desc

-- q4: compare the average purchase amount betwen standard and express shipping
select shipping_type, round(avg(purchase_amount),2) as "Average Purchase Amount"
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type
order by avg(purchase_amount)

-- q5: do subscribed customers spend more? compare average spend and total revenue between subscriber and non-subscribers
select 
	subscription_status,
	count(*) as "Number of customers",
	round(avg(purchase_amount), 2) as "Total spend",
	sum(purchase_amount)  as "Total Revenue"

from customer
group by subscription_status
order by avg(purchase_amount) desc

-- q6: which 5 products have the highest percentage of purchases with discount applied?
select top 5
    item_purchased,
    count(*) as total_purchases,
    sum(case when discount_applied = 'Yes' then 1 else 0 end) as discounted_purchases,
    cast(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) as decimal (5,2)) as "discount_percentage"
from customer
group by item_purchased
order by discount_percentage desc;


-- q7: segment customers into new, returning, and loyal based on their total
--number of previous purchases, and show the count of each segement
--previous purchase::: 1=new, 2-10 returning else loyal
select 
	customer_segment,
	count(*) as "Number of customers"
from (
	select 
		case
			when previous_purchases = 1 then 'New'
			when previous_purchases <=10 then 'Returning'
			else 'Loyal'
		end as customer_segment
	from customer
) as segments
group by customer_segment
order by count(*) desc

--q8: what are the top 3 most purchased product within each category'
with item_counts as (
select
	category,
	item_purchased,
	count(*) as total_orders,
	row_number() over (partition by category order by count(*) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3
order by category, item_rank

-- q9: are customers who are repeat buyers (more than 5 purchases) also likely to be subscribers?
select 
    case 
        when previous_purchases > 5 then 'Repeat Buyer'
        else 'Regular Buyer'
    end as buyer_type,
    count(*) as total_customers,
    sum(case when subscription_status = 'Yes' then 1 else 0 end) as subscribers,
    cast(100.0 * sum(case when subscription_status = 'Yes' then 1 else 0 end) / count(*) as decimal(5,2)) as subscriber_percentage
from customer
group by 
    case 
        when previous_purchases > 5 then 'Repeat Buyer'
        else 'Regular Buyer'
    end;


-- q10: what is the revenue contribution by age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc